version: '3.8'

services:
    api:
        build: .
        ports:
            - '8080:8080'
        networks:
            - default
        volumes:
            - .:/usr/src/app
        depends_on:
            - redis
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8080/api/health"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 5s
    redis:
        image: redis
        restart: always
        ports:
        - "6379:6379"
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 5s

networks:
    default:
